### PR TITLE
update iproj schema with IASP and SQL attributes

### PR DESCRIPTION
**Pull request by SanjulaGanepola**

### CODE REVIEW

**Comment by worksofliam** [comment]
LGTM :+1:

**Comment by worksofliam** [comment]
@SanjulaGanepola We will also need this page in the documentation updated with info on these new props: https://github.com/IBM/ibmi-bob/blob/master/docs/prepare-the-project/iproj-json.md

**Review by edmundreinhardt — APPROVED** [review]
Great!

**Comment by edmundreinhardt** [comment]
Liam,  I already updated that page  with these new properties last week.

> @SanjulaGanepola We will also need this page in the documentation updated with info on these new props: https://github.com/IBM/ibmi-bob/blob/master/docs/prepare-the-project/iproj-json.md

**Pull request merged**
