### PR TITLE
Add dtaq object

### PR DESCRIPTION
**Pull request by JDubbTX**

### CODE REVIEW

**Review by edmundreinhardt — CHANGES_REQUESTED** [review]
This is fantastic.
Our external test is to have any new file type or feature testable through 
git@github.com:IBM/bob-recursive-example.git

Would you mind adding a DTAQ example there and then we can merge this and release it.  Part of the release process is making sure that bob-recursive-example builds cleanly

**Review by edmundreinhardt — APPROVED** [review]
I will make the changes to bob-recursive-example
we want to do a release now

**Comment by JDubbTX** [comment]
Ohh shoot, I just made a PR on bob-recursive example here:  https://github.com/IBM/bob-recursive-example/pull/11  I guess you can just close that one, or merge it. doesn't hurt to have more than one dtaq.

Incidentally I tested this on my company partition and the dtaq seemed to work as intended, but several other objects seemed to have issues.

**Comment by edmundreinhardt** [comment]
I will take your example and work with it, thanks John!

**Pull request merged**
